// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopDB;

#nullable disable

namespace WorkshopDB.Migrations
{
    [DbContext(typeof(WorkshopDBContext))]
    [Migration("20221106044154_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkshopModels.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Day");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Inception of Workshop Program"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Weekday - typical day spent not being a millionaire"
                        });
                });

            modelBuilder.Entity("WorkshopModels.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2x4",
                            Price = 30.0,
                            StationId = 4,
                            Type = "Wood"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steel",
                            Price = 10.0,
                            StationId = 4,
                            Type = "Metal-Rod"
                        },
                        new
                        {
                            Id = 3,
                            Name = "steel",
                            Price = 20.0,
                            StationId = 4,
                            Type = "Sheet-metal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brick",
                            Price = 3.0,
                            StationId = 4,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brick",
                            Price = 8.0,
                            StationId = 4,
                            Type = "CinderBlock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Glass",
                            Price = 11.0,
                            StationId = 4,
                            Type = "Stained-Blue"
                        });
                });

            modelBuilder.Entity("WorkshopModels.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A dedicated station for cleaning. It is more efficient to clean things here, than anywhere else!",
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A universal Workbench. Your vice is here, stop using the floor to work on your projects...",
                            Name = "Workbench"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A random location with which none of your tools are present at ...because you didn't put them ... you suck; change.",
                            Name = "ToolWall"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A place for all the scrap material your not man enough to throw away",
                            Name = "Storage"
                        });
                });

            modelBuilder.Entity("WorkshopModels.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hammer",
                            Price = 20.0,
                            StationId = 3,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Saw",
                            Price = 15.0,
                            StationId = 3,
                            Type = "Hack"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drill",
                            Price = 80.0,
                            StationId = 3,
                            Type = "Cordless-Electric"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chisel",
                            Price = 5.0,
                            StationId = 3,
                            Type = "3 \""
                        },
                        new
                        {
                            Id = 5,
                            Name = "Saw",
                            Price = 150.0,
                            StationId = 3,
                            Type = "Mitre"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Drillbit",
                            Price = 13.0,
                            StationId = 3,
                            Type = "Forestner - 30 mm"
                        });
                });

            modelBuilder.Entity("WorkshopModels.WsProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WsProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dedicated cameras pointed at different stations to capture action and auto-sequence a video timeline.",
                            Name = "Video System"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Modify a pressure washer and combine it with the cnc system of a 3d printer to cut complex sheet metal programmatically (preferably while sleeping.)",
                            Name = "Waterjet"
                        });
                });

            modelBuilder.Entity("WorkshopModels.Material", b =>
                {
                    b.HasOne("WorkshopModels.Tool", null)
                        .WithMany("MaterialList")
                        .HasForeignKey("ToolId");
                });

            modelBuilder.Entity("WorkshopModels.Tool", b =>
                {
                    b.HasOne("WorkshopModels.Station", null)
                        .WithMany("ToolSets")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkshopModels.Station", b =>
                {
                    b.Navigation("ToolSets");
                });

            modelBuilder.Entity("WorkshopModels.Tool", b =>
                {
                    b.Navigation("MaterialList");
                });
#pragma warning restore 612, 618
        }
    }
}
